#!/usr/bin/env bash
set -e

cd $(dirname $0)/..

echo " Generating website to public directory"

scripts/get-repos

rm -rf public
git clone https://github.com/kassisol/kassisol.github.io.git public
cd public
git remote rm origin
git remote add origin git@github.com:kassisol/kassisol.github.io.git
cd ..

hugo
